title: National Research Foundation, Singapore (NRF)
url: https://www.nrf.gov.sg
favicon: /images/Tiy.jpg
colors:
  primary-color: "#d27f82"
  secondary-color: "#a23234"
  media-colors:
    - title: media-color-one
      color: "#f6e7cb"
    - title: media-color-two
      color: "#afd3df"
    - title: media-color-three
      color: "#b9a3d0"
    - title: media-color-four
      color: "#00838f"
    - title: media-color-five
      color: "#a1c069"
resources_name: Resources
description: The National Research Foundation, Singapore (NRF), set up on 1
  January 2006, is a department within the Prime Minister's Office. The NRF sets
  the national direction for research and development (R&D) by developing
  policies, plans and strategies for research, innovation and enterprise. It
  also funds strategic initiatives and develops R&D capabilities by nurturing
  research talent.
permalink: none
baseurl: ""
exclude:
  - travis-script.js
  - .travis.yml
  - README.md
  - package.json
  - package-lock.json
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - Gemfile
  - Gemfile.lock
include:
  - _redirects
defaults:
  - scope:
      path: ""
    values:
      layout: page
custom_css_path: /misc/custom.css
custom_print_css_path: /assets/css/print.css
paginate: 12
remote_theme: isomerpages/isomerpages-template@next-gen
safe: false
plugins:
  - jekyll-feed
  - jekyll-assets
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-remote-theme
staging: https://nrf-corp-staging.netlify.app
prod: https://nrf-corp-prod.netlify.app
shareicon: /images/isomer-logo.svg
is_government: true
facebook-pixel: ""
google_analytics: ""
linkedin-insights: ""
